name: CARLOS VILAR. ARQUITECTO SENSIBLE
favicon: null
layout_spectrum: 0.68892
typography_spectrum: 0.15718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1eed3'
    - '#848175'
    - '#0c003b'
    - '#5a584e'
    - '#83b0b8'
  brandStrength: 0.4375
  lightness: 0.6656275459099561
  saturation: 0.1875
  rhythmicContrast: 0.35076602222397923
purpose: []
