name: CARLOS VILAR. ARQUITECTO SENSIBLE
favicon: null
layout_spectrum: 0.68892
typography_spectrum: 0.58534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0a1914'
    - '#b2201c'
    - '#d9844b'
    - '#3d7879'
  brandStrength: 0.5625
  lightness: 0.6656275459099561
  saturation: 0.1875
  rhythmicContrast: 0.35076602222397923
purpose: []
