name: CARLOS VILAR. ARQUITECTO SENSIBLE
favicon: null
layout_spectrum: 0.69471
typography_spectrum: 0.64706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#454545'
    - '#000000'
    - '#aaaaaa'
    - '#ffffff'
    - '#00ffff'
  brandStrength: 0.4375
  lightness: 0.6656275459099561
  saturation: 0.1875
  rhythmicContrast: 0.35076602222397923
purpose: []
